# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'RoboSlogan.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  AppSettings.Token: $(discordSecret)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'RoboSlogan/RoboSlogan.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
    fileType: 'json'
    targetFiles: '**/appsettings.json'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'

